# -*- coding: utf-8 -*-
"""AI_Sentiment_Analyzer

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1M-Yhl7lWqIG6yIcVsZl84GP74nnKisJv
"""

!pip install transformers torch pandas matplotlib

from transformers import pipeline

classifier = pipeline("sentiment-analysis")

print("Model Loaded Successfully!")

review = "This product is amazing and works perfectly."

result = classifier(review)

print(result)

review = input("Enter a review: ")

result = classifier(review)

print("\nSentiment:", result[0]['label'])
print("Confidence Score:", round(result[0]['score'], 4))

import pandas as pd

reviews = [
    "This product is amazing.",
    "I hate this service.",
    "The experience was average.",
    "Very good quality.",
    "Worst purchase ever."
]

results = []

for review in reviews:
    sentiment = classifier(review)[0]

    results.append([
        review,
        sentiment['label'],
        round(sentiment['score'], 4)
    ])

df = pd.DataFrame(
    results,
    columns=["Review", "Sentiment", "Confidence"]
)

df

import matplotlib.pyplot as plt

sentiment_counts = df["Sentiment"].value_counts()

plt.figure(figsize=(5,5))
plt.pie(
    sentiment_counts,
    labels=sentiment_counts.index,
    autopct="%1.1f%%"
)

plt.title("Sentiment Distribution")
plt.show()

# Save results to CSV

df.to_csv("sentiment_results.csv", index=False)

print("Results saved successfully!")

from google.colab import files

files.download("sentiment_results.csv")